version: '3'

services:
  web:
    build: .
    container_name: trading_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ai_trading:/app/ai_trading
      - ./web_app:/app/web_app
      - ./data:/app/data
      - ./tradingview:/app/tradingview
    depends_on:
      - redis
      - db
    command: python -m web_app.app

  redis:
    image: redis:alpine
    container_name: trading_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: trading_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tests:
    build: .
    container_name: trading_tests
    volumes:
      - ./ai_trading:/app/ai_trading
      - ./tests:/app/tests
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: python -m pytest tests/ -v

volumes:
  postgres_data: 