name: AI Trading Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader punkt wordnet
        
    - name: Run AI Trading unit tests
      run: |
        pytest ai_trading/tests/test_enhanced_collector.py -v
        pytest ai_trading/tests/test_enhanced_preprocessor.py -v
        pytest ai_trading/tests/test_enhanced_news_analyzer.py -v
        pytest ai_trading/tests/test_social_analyzer.py -v
        pytest ai_trading/tests/test_sentiment_integration.py -v
    
    - name: Run Web App tests
      run: |
        pytest tests/web_app/test_transaction_service.py -v
        pytest tests/web_app/test_routes.py -v
        pytest tests/web_app/test_price_service.py -v
    
    - name: Run coverage report
      run: |
        pytest --cov=ai_trading --cov=web_app --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
    
    - name: Check code formatting
      run: |
        pip install black
        black --check ai_trading/ web_app/
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 ai_trading/ web_app/ 