name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock requests flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run AI Trading tests
      run: |
        pytest tests/ai_trading/ -v
      env:
        CRYPTO_API_KEY: ${{ secrets.CRYPTO_API_KEY }}
        CRYPTO_API_SECRET: ${{ secrets.CRYPTO_API_SECRET }}
    
    - name: Run Web App tests
      run: |
        pytest tests/web_app/ -v
      env:
        CRYPTO_API_KEY: ${{ secrets.CRYPTO_API_KEY }}
        CRYPTO_API_SECRET: ${{ secrets.CRYPTO_API_SECRET }}
        FLASK_ENV: testing 